### PR TITLE
Dealing with different types of imports

### PR DESCRIPTION
**Pull request by syedalimohsinbukhari**
Several import types to deal with include,
- [ ] `from package import module`
- [ ] `from package import module1, module2`
- [ ] `from package import module1 as _module1, module2 as _module2`
- [ ] `from . import package`
- [ ] `from . import package1, package2`
- [ ] `from package.subpackage import file`
- [ ] `import package`
- [ ] `import package as _package`
- [ ] Imports in `try/except` block
- [ ] Avoid `from` and `import` in strings/docstrings.

### CODE REVIEW

**Comment by syedalimohsinbukhari** [comment]
1. `from . import package`
2. `from . import package1, package2`

It should be included in `imports_` not `from_imports` because they're importing from the base directory.

**Comment by DamnUi** [comment]
Interesting that does make a lot for sense



> 1. `from . import package`
> 2. `from . import package1, package2`
> 
> It should be included in `imports_` not `from_imports` because they're importing from the base directory.

**Review by DamnUi — APPROVED** [review]
This file is not much of a code change more of it looking prettier, grammer.
Really good for a start, Thanks again!

**Comment by syedalimohsinbukhari** [comment]
> This file is not much of a code change more of it looking prettier, grammer. Really good for a start, Thanks again!

I hadn't made any major changes yet :laugh: it was still in development phase ..

**Pull request merged**
