### PR TITLE
Scrapping various things in PyStats

### PR DESCRIPTION
**Pull request by AstrophysicsAndPython**
- [ ] imports
  - [x] `import package`
  - [x] `import package as pkg`
  - [x] `from package import file`
  - [x] `from package.subpackage import file as abbrev`
  - [ ] `import package.subpackage as abbrev`
- [x] variables
  - [x] `variable = ` # include spaces in the beginning as well
  - [x] `self.variable = `
- [ ] get top N number of variables

### CODE REVIEW

**Comment by AstrophysicsAndPython** [comment]
Work in progress

**Comment by AstrophysicsAndPython** [comment]
Variable scrapping output from commit https://github.com/DamnUi/PyStats/pull/2/commits/1c83434b83f47d53dced51a8fb965012899e7bfc

image

**Review by DamnUi — APPROVED** [review]
Holy shit this is huge

**Comment by DamnUi** [comment]
Im not merging it as i dont have time rn but you can Astro

**Comment by AstrophysicsAndPython** [comment]
We don't have to merge it RN, it is still a work in progress. I'll let you know when I'll finish working on it and when it'll be time to merge it. Cheers!

**Comment by DamnUi** [comment]
> We don't have to merge it RN, it is still a work in progress. I'll let you know when I'll finish working on it and when it'll be time to merge it. Cheers!

i, See

**Comment by DamnUi** [comment]
Also the --onefile parameter seems to be not working properly and im not sure about the reason but pretty sure its a simple fix

**Comment by AstrophysicsAndPython** [comment]
My man 😂 you merged it right after I said we don't have to merge it.

**Comment by AstrophysicsAndPython** [comment]
> Also the --onefile parameter seems to be not working properly and im not sure about the reason but pretty sure its a simple fix

That's working fine for me,

**Comment by DamnUi** [comment]
> My man 😂 you merged it right after I said we don't have to merge it.

sometimes i forget to read lol and im kinda new to github sorry about that

**Comment by DamnUi** [comment]
> > Also the --onefile parameter seems to be not working properly and im not sure about the reason but pretty sure its a simple fix
> 
> That's working fine for me, I think you might be doing a `--onefile` instead of `-onefile`.

yeah seems like that fixed it on my end for now

**Comment by AstrophysicsAndPython** [comment]
> > My man 😂 you merged it right after I said we don't have to merge it.
> 
> sometimes i forget to read lol and im kinda new to github sorry about that

It happens, no big deal.

**Pull request merged**
